# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_ip = QtWidgets.QLabel(self.centralwidget)
        self.label_ip.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.label_ip.setObjectName("label_ip")
        self.textEdit_search = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_search.setGeometry(QtCore.QRect(100, 65, 651, 31))
        self.textEdit_search.setObjectName("textEdit_search")
        self.label_search = QtWidgets.QLabel(self.centralwidget)
        self.label_search.setGeometry(QtCore.QRect(10, 70, 91, 17))
        self.label_search.setObjectName("label_search")
        self.plainTextEdit_result = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_result.setGeometry(QtCore.QRect(10, 100, 780, 451))
        self.plainTextEdit_result.setReadOnly(True)
        self.plainTextEdit_result.setObjectName("plainTextEdit_result")
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(760, 25, 31, 71))
        self.btn_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon)
        self.btn_search.setObjectName("btn_search")
        self.comboBox_ip = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ip.setEnabled(True)
        self.comboBox_ip.setGeometry(QtCore.QRect(100, 30, 590, 25))
        self.comboBox_ip.setEditable(False)
        self.comboBox_ip.setMaxVisibleItems(100)
        self.comboBox_ip.setObjectName("comboBox_ip")
        self.btn_add_ip = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_ip.setGeometry(QtCore.QRect(700, 30, 25, 25))
        self.btn_add_ip.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_ip.setIcon(icon1)
        self.btn_add_ip.setObjectName("btn_add_ip")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.menuhelp.addAction(self.actionhelp)
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Search"))
        self.label_ip.setText(_translate("MainWindow", "Select pc ip"))
        self.textEdit_search.setStatusTip(_translate("MainWindow", "Search field"))
        self.label_search.setText(_translate("MainWindow", "Search string"))
        self.plainTextEdit_result.setStatusTip(_translate("MainWindow", "Result list"))
        self.btn_search.setStatusTip(_translate("MainWindow", "Search"))
        self.menuhelp.setTitle(_translate("MainWindow", "menu"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionhelp.setStatusTip(_translate("MainWindow", "Show help menu"))
        self.actionhelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
